### ISSUE TITLE
video player

### ISSUE THREAD

**Issue by minicrack56** [alx-xlx/goindex#10]
we cannot stream videos

**Comment by alx-xlx** [comment]
are you streaming on a Mobile browser or a PC browser, also mention which specific browser you are using

**Comment by minicrack56** [comment]
I'm using Chrome on my computer

**Comment by minicrack56** [comment]
and also the button play and download at the bottom of the video that i want to watch do not work

**Comment by minicrack56** [comment]
thanks it is working now
