### ISSUE TITLE
donwa classic mode broken password dialogue

### ISSUE THREAD

**Issue by JamesHarbon** [alx-xlx/goindex#14]
for your donwa worker js in classic mode, i have the "root_pass": ""
but at the site, its still asking for a password. If you put empty password in the dialogue, it will direct me to home browser page

im using edge chromium browser

at chrome, is you enter nothing in the dialogue/prompt it will just stuck

**Comment by alx-xlx** [comment]
make sure to clear cache each time you edit and deploy the script

**Comment by JamesHarbon** [comment]
man i forgot i put .password file in the folder long time ago when i first try gindex, nowaday they have option to turn off .password stuff

this is sure embarrassing
