### ISSUE TITLE
does goindex support with shared drivers?

### ISSUE THREAD

**Issue by troke12** [alx-xlx/goindex#24]
as you know theres only option for root folder not for shared folder, i wanna integrate my shared folder with goindex

![img](https://cdn.discordapp.com/attachments/408950289962369025/749054720102105098/unknown.png)

**Comment by alx-xlx** [comment]
replace root with folder/shared-drive ID

**Comment by troke12** [comment]
where i can find the shared-drive id?

**Comment by alx-xlx** [comment]
example:

Shared Drive OR Shared Folder - `https://drive.google.com/drive/u/0/folders/0XXXL6Q000001119PVA`

`0XXXL6Q000001119PVA` is your **Shared Drive ID**, it is also called **Folder ID**

**Comment by troke12** [comment]
oh i got it !!! thanks!
