### ISSUE TITLE
Quick Fix: Remove leaking of the Google Drive ID

### ISSUE THREAD

**Issue by TA40** [alx-xlx/goindex#27]
I found out that you can see the Google Drive IDs of the files/folders when you make a request to list a folder.
Changing `files(id, name, mimeType,` to `files(name, mimeType,` on line 565 (folder listing) and 680 (search) fixes it as these are not used at all.
The website still runs absolutely fine. Just without the ID.

Would it be possible to change this in your Auto Builder?

**Comment by alx-xlx** [comment]
Fixed - [index.js](https://raw.githubusercontent.com/alx-xlx/goindex/31fabf3d7ff221ff34aaaf23e63a1a5a49e40b4f/goindex-acrou/go2index/index.js)
Updated - [goindex.glitch.me](https://goindex.glitch.me/)

**Comment by TA40** [comment]
@alx-xlx Just experimented a bit and found out that line 680 needs the id to link to the files after the search.
Unfortunately I oversaw that, could you put it back in?

Best would be to just encrypt the ids, then decrypt them, but importScripts does not work on CF Workers unfortunately so CryptoJS is not available so easily.
