### ISSUE TITLE
How to add multiple team drives

### ISSUE THREAD

**Issue by ultramyslixs** [alx-xlx/goindex#34]
I have over 20 shared drives, is there a way to let me add all of them at once? How do I put them in the goindex.js?

**Comment by pseudokawaii** [comment]
@ultramyslixs Afaik, goindex.js doesn't support multiple drives. You may use [This one]( https://github.com/Aicirou/goindex-theme-acrou) if you want to add multiple drives on a single script.

**Comment by ultramyslixs** [comment]
ok, thank you!
