### ISSUE TITLE
How to upload file?

### ISSUE THREAD

**Issue by quocthinhvo** [alx-xlx/goindex#44]

**Comment by alx-xlx** [comment]
You can use the [goindex-vue.js](https://github.com/alx-xlx/goindex/blob/2.0.8-darkmode-0.1/goindex-vue.js) to upload files

you can use GUI to upload
OR
if CLI is your thing then use HTTP requests

Example:
## gdindex_upload.py
```py
## Python Example
import requests

to_upload = "https://i.imgur.com/8w2KDrG.gif"
# "upload: true" in the script
baseURL = "https://gdindex-dark.teamsdrives.workers.dev/"
fileName = "goindex.gif"
# "folder1/folder2/goindex.gif"
teamDriveID = "0ANCHcQq-8cmvUk9PVA" # Default - "root"

URL = baseURL + "/" + fileName + "?rootId=" + teamDriveID + "&url=" + to_upload
r = requests.put(URL)
print(r.text)
```

**Comment by quocthinhvo** [comment]
thanks. I will try. @alx-xlx

**Comment by jrchintu** [comment]
sorry to restart thread but how to use this script or shall i need extra server
