### ISSUE TITLE
Can't open a folder or download a file if a searched for something

### ISSUE THREAD

**Issue by IDontKnow218** [alx-xlx/goindex#51]
One of my friends has a goindex website. He has lots of stuff so I have to search for anything I want. But if I searched, I can't access any folder or download a file. Is there any fix for this?

**Comment by alx-xlx** [comment]
it is a bug that has to be fixed
thank you for notifying

**Comment by alx-xlx** [comment]
@IDontKnow218 it is fixed, use the new script
