### ISSUE TITLE
Search Bar Is Not Working For Team Drives!

### ISSUE THREAD

**Issue by Itz-fork** [alx-xlx/goindex#61]
GoIndex's search bar is working for " **root** " id but not in team drive! So Any Fix For that?

**Comment by alx-xlx** [comment]
@Itz-fork paste the script that you are using, remove any credentials

**Comment by Itz-fork** [comment]
> @Itz-fork paste the script that you are using, remove any credentials

Sorry My Problem! I found a fix for that ! Thanks :)

**Comment by risfat** [comment]
@Itz-fork How did u fixed that... I'm also having the same issue...Any suggestions would be most appreciated.
