### ISSUE TITLE
Source code of goindex.glitch.me

### ISSUE THREAD

**Issue by TA40** [alx-xlx/goindex#65]
Hi, could you open the source code of the webpage?
If I click on "https://glitch.com/edit/#!/goindex", it outputs an error as it is set to private.
Thanks.

**Comment by alx-xlx** [comment]
the code is always available at https://github.com/alx-xlx/goindex/tree/master/goindex-acrou/goindex-builder-code

however, I had forgotten to make https://glitch.com/edit/#!/goindex public too
Thanks

**Comment by TA40** [comment]
Thank you very much!
