### ISSUE TITLE
Sorting of numbers in Firefox

### ISSUE THREAD

**Issue by necaran** [alx-xlx/goindex#87]
By default, files are sorted like this.
```
A01.txt
A02.txt
B01.txt
B02.txt
```

But in Firefox it became like this.
```
A02.txt
A01.txt
B02.txt
B01.txt
```
Somehow only the numbers are in descending order.

I am running version 2.0.8-darkmode-0.1, but I am experiencing the same issue on other people's sites.

**Comment by DestinoLol** [comment]
Same problem here

**Comment by ThePhantom00** [comment]
any solutions?
